language: node_js
node_js:
- '6'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script:
#- npm run lint
#- npm run test
deploy:
  provider: s3
  access_key_id: "AKIAI7MKGPRHR65CWF4Q"
  secret_access_key:
    secure: "YXq32w2uR6/U4ScCK6M7kMq+1hvKnMweokaZuvEYQ7pZemlCMG818IOB1d54Kk1gk/GdvSMkUsqjo3PxoHCCGXIVjgChPenzGaDiA8Hzr8KaLGjs9pkrzyCrymQ5yiPZVfO/lcTUlH9qcJdTlI8HuxskIunVfV3B3KUsh+rgV3JWk9QjGcR2HVbUXOVXTQf5GSY1K1K1cZkNgIplTnyVcnpYG47rArqcPAfJW0ZvGEyoJZ5lzCID+V/MZjdo/pSNzQsllaad93Lh9ZjWmZDXOqqPQPVgXr25TuKNWXDw+233Z4084C+Qa8a0BSs2KqAYfWuNUIewtNyFVwDeQO/9upnY/dkV5tQKRc1BquPZJGzXpGYGFlvNGeq8q7gqIGZvLcqgNPrv2JsGrvOVCNJtp2ubb+3pkvlUIeopC7lHzRNVFNM6iLDHwDAUXFrb+XMpedCwMTU2OZW8Ume2Nq8fkrRR3HuWBvfoxF0XueC2BrsT3hpySeMI4udEEV4HsOlag37BPAimdH1aNXoxnjDtl0/wjGXmA60FqdRZ5CJK/oV/pWWpO4Q36qKj11k2oin25xDa/Db6aLlcZYOK3mTRPgIlJZJtJYynkqyop2qdOGBxW62x4RLblNb3hScO2jxgF2tCqgkwyeKNGa/Wphf2URC3vSBUcNT/rDMMCK2CD6c="
  bucket: "personalayee"
  skip_cleanup: true
  local_dir: public
