language: node_js
node_js:
- '6'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script:
- npm run lint
- npm run test
deploy:
  provider: s3
  access_key_id:
    secure: Sm5SJ6dwAJKkbHiHaYsEcgqH7AubOvcn1/cWgxhJ2zKUWG9mjYQEzdXnrSvoFbRZFIq8r7vrxfctfwvRXOiqfeOIRqISyTm8YGcdEsny4xIEFiJ0PAixU+xrdFE/vgMTlnt8+Y7hU3yqvoqx7QGgEnOS5ipXC6f0hIV7K0Ng4TLsWG1RGoT5IOQeoskPcX6H+b+Tve6wxV7jM3xizo4wdr1q6Os+HagUFe20gcH6vDQo0DbZhiag01hK69dMRE6FL1eulkzeaCltlyD5tq3s86BKiRBiJdE2+PkDAUAagCckwIq/GnNbBWZ2ryAIfpmRFjw+7xG0LZTM2Q1aCbJYi+wLIZqXPW/CbmwidtZBpB3gxWrzCY+rD1PHYKiRr8YW8A//jVNEHyvwq9u2apIzmc5oMTnj7LWkVJNrAzbefEt3pdT2gKBdkkS59WRqPYZotkGKd7D7Z8I5jt1KTmBtd8c4jh4wT0ROligGRgEWF0jFZ9VZpYJKpZFA147tKKAkzBqNd4Yx5qGlAt63+JLrRynlntjN+5/7xAZBMGRYiEtczusErDAxuBn+uzL2LwyrvjiSZKxuE3TQgqHUXTslNe7YN/u4jn9K4805e0C3XW9otEe1icw3j0j3IKaqeWfYnb5GrNX5LUDhL5aTMxWReW3J0vg0peIepIDcRt56/LU=
  secret_access_key:
    secure: YXq32w2uR6/U4ScCK6M7kMq+1hvKnMweokaZuvEYQ7pZemlCMG818IOB1d54Kk1gk/GdvSMkUsqjo3PxoHCCGXIVjgChPenzGaDiA8Hzr8KaLGjs9pkrzyCrymQ5yiPZVfO/lcTUlH9qcJdTlI8HuxskIunVfV3B3KUsh+rgV3JWk9QjGcR2HVbUXOVXTQf5GSY1K1K1cZkNgIplTnyVcnpYG47rArqcPAfJW0ZvGEyoJZ5lzCID+V/MZjdo/pSNzQsllaad93Lh9ZjWmZDXOqqPQPVgXr25TuKNWXDw+233Z4084C+Qa8a0BSs2KqAYfWuNUIewtNyFVwDeQO/9upnY/dkV5tQKRc1BquPZJGzXpGYGFlvNGeq8q7gqIGZvLcqgNPrv2JsGrvOVCNJtp2ubb+3pkvlUIeopC7lHzRNVFNM6iLDHwDAUXFrb+XMpedCwMTU2OZW8Ume2Nq8fkrRR3HuWBvfoxF0XueC2BrsT3hpySeMI4udEEV4HsOlag37BPAimdH1aNXoxnjDtl0/wjGXmA60FqdRZ5CJK/oV/pWWpO4Q36qKj11k2oin25xDa/Db6aLlcZYOK3mTRPgIlJZJtJYynkqyop2qdOGBxW62x4RLblNb3hScO2jxgF2tCqgkwyeKNGa/Wphf2URC3vSBUcNT/rDMMCK2CD6c=
  bucket: personalayee
  skip_cleanup: true
  local_dir: public
